//GLOBAL SETTINGS
const MAX_HEIGHT = 200;
const MAX_WIDTH = 600;
const GROUND_HEIGHT = 30;

//PLAYER SETTINGS
const GRAVITY = 60;
const MAX_UP_ROTATION = Math.PI/3.5;
const GROUND_CRASH_SEIL = -50;
const SCORE_PER_PIXEL = 0.2;
const FUEL_PERCENT_PER_SECOND = 2;
const REFUEL_PERCENT_PER_SECOND = 20;

//SPRITE GENERATION SETTINGS
const MIN_GENERATION_FREQUENCY = 0.1;
const MAX_GENERATION_FREQUENCY = 1;
const GENERATION_FREQUENCY_GAP = 0.03;
const MIN_VEHICLE_GENERATION_HEIGHT = MAX_HEIGHT * 2/3;
const VEHICLE_GENERATION_HEIGHT_GAP = MAX_HEIGHT * 1/4

//RENDERER SETTINGS
const PLAYER_DISPLAY_X = 20;